### ISSUE TITLE
about window looks weird in 1.8

### ISSUE THREAD

**Issue by tessus** [bhaller/Jiggler#12]
macOS 10.15.6

This is really not an important issue. I just wanted to raise it, because it might be an indicator for something else.

# 1.7

![Screen Shot 2020-07-28 at 18 42 22](https://user-images.githubusercontent.com/223439/88745035-006fc780-d117-11ea-942a-79b2d9af66d9.png)

# 1.8

![Screen Shot 2020-07-28 at 18 42 33](https://user-images.githubusercontent.com/223439/88745654-96582200-d118-11ea-8c00-8c7430f61e42.png)

**Comment by bhaller** [comment]
Ah, dark mode.  OK.  I thought I tested it with dark mode, but maybe I forgot to.  Well, I'll leave this issue open for the next time I revise Jiggler, but obviously it isn't a high priority.  Thanks for the report, though; it will get fixed eventually.

**Comment by e5faf2** [comment]
Fixed in #14

**Comment by bhaller** [comment]
Accepted, fixed, not sure why this didn't get auto-closed.  Thanks!

**Comment by kctessarek-tc** [comment]
Unfortunately this is still not fixed. This is how it looks like on macOS 10.15.7 with Jiggler 1.9:

![image](https://user-images.githubusercontent.com/64483348/129318199-4ad2b49c-a47f-49d4-abcf-280a5e0aa17c.png)

Once again, this is not important, just surprising that the issue still persists.

**Comment by tessus** [comment]
Unfortunately this is still not fixed. This is how it looks like on macOS 10.15.7 with Jiggler 1.9:

![image](https://user-images.githubusercontent.com/64483348/129318199-4ad2b49c-a47f-49d4-abcf-280a5e0aa17c.png)

Once again, this is not important, just surprising that the issue still persists.

**Comment by bhaller** [comment]
Sigh.  It looked good when I tested it on Big Sur, but maybe that fix doesn't work right on 10.15?  OK, thanks for the report.

**Comment by bhaller** [comment]
There may have been a problem back on 10.15, but that is ancient history.  AFAICT the about panel looks fine for macOS 11 and later, so I'm going to close this.  Of course reopen it if somebody is still seeing this problem on a modern version of macOS.
