### ISSUE TITLE
Jiggler "Zen mode" not functioning on MacOS 26.0 (Tahoe)

### ISSUE THREAD

**Issue by steventrotter** [bhaller/Jiggler#34]
The app is not preventing my Mac from sleeping while running 26.0 Beta (25A5316i).

**Comment by bhaller** [comment]
Usually this turns out to be an error in preferences settings, or Jiggler is not active (no checkmark next to "Jiggler Enabled" in its menu, and a dimmed icon in the menu bar, meaning that it is not enabled).  But maybe Apple has actually broken Jiggler; always possible.  I don't have any cycles to look into it for a while, and I'm not on this macOS version anyway so I can't look into it anyway, sorry.

**Comment by bhaller** [comment]
This issue was fixed by @MarinSavca and @kumichou; thanks very much to both of them for their work!  The Jiggler 1.10 release is now available on the Releases tab (https://github.com/bhaller/Jiggler/releases/tag/v1.10), and you can download it directly from there.  It'll be up on the Stick Software website soon.  Sorry that it took so long to get a fix out; I'm not on Tahoe myself yet so I couldn't reproduce it or test it, and life is quite busy lately.  Please comment and reopen if it appears that the new version doesn't fix the problem.  Thanks for the helpful comments above.

**Comment by bhaller** [comment]
Unfortunately, a user reports that this issue is not fixed in Jiggler 1.10. User report: "Just FYI - after installing v1.10 on Macbook Pro 2021 (M1 Max processor and iOS Version 26.1 (25B78)) - the "Zen jiggle" functionality is still not working. The other two options work as expected." Reopening. I am not on Tahoe yet, and don't expect to be for some time yet, so I can't investigate this myself. Tagging @MarinSavca and @kumichou since they provided the fix that shipped in 1.10 (which might very well have fixed the issue for some users, but apparently not for all).

Others who are reading this: it would be very useful for you to post here on whether Zen jiggle now works correctly for you on Tahoe. Please post details about your system that might illuminate why your experience with Zen jiggle might be different from that of others (macOS version, hardware, any other weird software you're running that might interfere with Jiggler, any usual accessibility system settings you use), a snapshot of your Jiggler preferences panel, whether you notice anything specific about Jiggler's behavior that might be relevant (does the overlay window with Jiggler's icon display when Zen jiggling? does the icon in the menu bar turn green?). Also specify whether Zen jiggle fails to prevent screensaver activation, display sleep, system sleep, or all three.

Let's get to the bottom of this!

**Comment by music86-bg** [comment]
Hi Everyone, I am the one who reported that Zen jiggle is still not working properly. 

A little more details:
- the Zen jiggle DOES prevent MacOS from going into sleep (i.e. my screen does not turn off), but...
- it DOES NOT prevent MS Teams from moving from "Available" to "Away" state. I even tried to set "Teams" as a condition in the setting... still does not work as expected.
 
<img width="473" height="75" alt="Image" src="https://github.com/user-attachments/assets/0959962c-cae0-45eb-8306-4da4ccd64d96" />

Please, let me know if I can help with more details.

**Comment by bhaller** [comment]
> Hi Everyone, I am the one who reported that Zen jiggle is still not working properly.
> 
> A little more details:
> 
> * the Zen jiggle DOES prevent MacOS from going into sleep (i.e. my screen does not turn off), but...
> * it DOES NOT prevent MS Teams from moving from "Available" to "Away" state. I even tried to set "Teams" as a condition in the setting... still does not work as expected.

Aha, I see.  OK.  That means that this issue, which was about "Zen mode" not working at all on Tahoe, is in fact fixed.  I've opened a new issue for this problem with Teams at https://github.com/bhaller/Jiggler/issues/43 and will follow up there.

To those reading this thread: if you see a problem with Jiggler's "Zen mode" failing to keep your machine awake at all, please reopen and comment as discussed above.  For an issue with Teams specifically, please see issue #43.  Thanks!
